### ISSUE TITLE
why compare_exchange_strong() in a loop?

### ISSUE THREAD

**Issue by Andriy06** [max0x7ba/atomic_queue#57]
out of curiousity, why `compare_exchange_strong()` is used in loops where I believe `compare_exchange_weak()` would be sufficient?  based on benchmarks results? do you still have them or remember details?

and while I have you here :) why platform dependent definition of `CACHE_LINE_SIZE`? any known issues with `std::hardware_destructive_interference_size`?

thanks

**Comment by max0x7ba** [comment]
> out of curiousity, why `compare_exchange_strong()` is used in loops where I believe `compare_exchange_weak()` would be sufficient? based on benchmarks results? do you still have them or remember details?

It is documented in [README](https://github.com/max0x7ba/atomic_queue/blob/master/README.md?plain=1#L111). To prevent caller's non-atomic stores and loads from being reordered across `push` and `pop`.

> and while I have you here :) why platform dependent definition of `CACHE_LINE_SIZE`? any known issues with `std::hardware_destructive_interference_size`?

This library requires C++14. `std::hardware_destructive_interference_size` is a C++17 feature.

**Comment by Andriy06** [comment]
thanks for the quick reply. Sorry I still don't get it. The linked line of README talks about "synchronising with" between `push` and `pop` that, I believe, is governed solely by the memory order. I believe that `_strong` version is the same as `_weak` regarding reordering guarantees, and the only difference is that it prevents spurious failures, which is not a problem in this case as on failure the code will retry in a loop. What am I missing?

**Comment by max0x7ba** [comment]
Memory order is not about spurious failures. 

Memory order is about ordering of other non-atomic loads and stores with respect to an atomic operation. I don't think I can explain it better than https://en.cppreference.com/w/cpp/atomic/memory_order does.

**Comment by max0x7ba** [comment]
> out of curiousity, why `compare_exchange_strong()` is used in loops where I believe `compare_exchange_weak()` would be sufficient? based on benchmarks results? do you still have them or remember details?

> I believe that _strong version is the same as _weak regarding reordering guarantees, and the only difference is that it prevents spurious failures, which is not a problem in this case as on failure the code will retry in a loop.

Ah, this is about `compare_exchange_strong` vs `compare_exchange_weak`, not the memory order. My mistake.

The library originated on x86-64 platform where both the weak and strong versions generate identical assembly code. Reviewing the generated assembly code on other platforms supported today reveals that on power64 the strong version generates an extra retry loop, https://godbolt.org/z/rvaj4oYGh

Since this library implements its own retry loops, this extra retry loop introduced by the strong version is unnecessary and should be removed. As you astutely spotted and kindly made an effort to bring this issue to my attention.

If you'd like to submit a pull request addressing this issue I'd be delighted to merge it.

**Comment by Andriy06** [comment]
glad that misunderstanding is resolved :) will submit a pull request in a bit

**Comment by max0x7ba** [comment]
Thank you for your contribution.

**Comment by max0x7ba** [comment]
> any known issues with `std::hardware_destructive_interference_size`?

Just an FYI, clang-18.1.3 still doesn't provide `std::hardware_destructive_interference_size` in C++20 mode.
